<?php

namespace Database\Seeders;

use App\Models\Registration;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class RegistrationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $samples = [
            [
                'type' => 'delegate',
                'full_name' => 'Capt. Rajesh Varma',
                'email' => 'rajesh.varma@mazagondock.gov.in',
                'phone' => '+91 98201 44521',
                'organization' => 'Mazagon Dock Shipbuilders Ltd',
                'designation' => 'General Manager - Fleet Technical Services',
                'industry' => 'Shipbuilding & Defense',
                'pass_tier' => 'VIP Executive Pass',
                'message' => 'Interested in attending high-level port decarbonization panels and shipbuilding procurement sessions.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subHours(2),
            ],
            [
                'type' => 'speaker',
                'full_name' => 'Elena Rostova',
                'email' => 'e.rostova@portofrotterdam.nl',
                'phone' => '+31 10 252 1000',
                'organization' => 'Port of Rotterdam Authority',
                'designation' => 'Director of Sustainable Energy & Green Bunkering',
                'industry' => 'Port Authority / Clean Energy',
                'pass_tier' => 'Speaker Pass',
                'message' => 'Presenting keynote slides on European shore power grids and green hydrogen supply chain.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subHours(5),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Arun Sundaram',
                'email' => 'arun.sundaram@lntecc.com',
                'phone' => '+91 94440 18234',
                'organization' => 'Larsen & Toubro (Heavy Civil Infrastructure)',
                'designation' => 'Chief Project Engineer - Marine Structures',
                'industry' => 'Port Construction & Infrastructure',
                'pass_tier' => 'VIP Executive Pass',
                'message' => 'Attending deep draft port development sessions and berth expansion symposium.',
                'status' => 'pending',
                'created_at' => Carbon::now()->subHours(7),
            ],
            [
                'type' => 'sponsor',
                'full_name' => 'Vikram Singhania',
                'email' => 'v.singhania@greatship.com',
                'phone' => '+91 99308 77123',
                'organization' => 'The Great Eastern Shipping Co Ltd',
                'designation' => 'Vice President - Chartering & Commercial',
                'industry' => 'Commercial Shipping & Tanker Fleet',
                'pass_tier' => 'Sponsor Tier (Associate)',
                'message' => 'Finalizing sponsorship package and table-top exhibition booth location.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subHours(12),
            ],
            [
                'type' => 'awards',
                'full_name' => 'Dr. Meera Nambiar',
                'email' => 'meera.nambiar@iitm.ac.in',
                'phone' => '+91 94441 55678',
                'organization' => 'IIT Madras - Dept. of Ocean Engineering',
                'designation' => 'Professor & Head of Marine Hydrodynamics Laboratory',
                'industry' => 'Maritime Academia & R&D',
                'pass_tier' => 'Standard Delegate Pass',
                'message' => 'Nominated for Best Maritime University / R&D Institute of the Year.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subHours(18),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'David Sterling',
                'email' => 'david.sterling@coreaxis.ae',
                'phone' => '+971 4 388 9901',
                'organization' => 'Core Axis Maritime Solutions L.L.C',
                'designation' => 'Managing Director - Middle East Operations',
                'industry' => 'Offshore Marine Solutions',
                'pass_tier' => 'VIP Executive Pass',
                'message' => 'Exploring Indian Ocean trade partnerships and offshore logistics integration.',
                'status' => 'pending',
                'created_at' => Carbon::now()->subHours(22),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Kavita Chawla',
                'email' => 'k.chawla@absmarine.com',
                'phone' => '+91 98112 34509',
                'organization' => 'ABS Marine Services Ltd',
                'designation' => 'Head of Safety & Marine Operations',
                'industry' => 'Offshore Support Vessels',
                'pass_tier' => 'Standard Delegate Pass',
                'message' => 'Reviewing lunch & coffee sponsorship collateral and attending award ceremony.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subDay(),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Mohammed Al-Husseini',
                'email' => 'alhusseini@arabianshipping.com',
                'phone' => '+966 50 123 4567',
                'organization' => 'Arabian Shipping & Feeder Lines',
                'designation' => 'Commercial Line Manager',
                'industry' => 'Feeder Services & Container Logistics',
                'pass_tier' => 'Standard Delegate Pass',
                'message' => 'Requesting invoice with GST/VAT details for corporate travel clearance.',
                'status' => 'pending',
                'created_at' => Carbon::now()->subDays(2),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Johnathan Keller',
                'email' => 'j.keller@dnv.com',
                'phone' => '+47 67 57 99 00',
                'organization' => 'DNV Maritime Advisory',
                'designation' => 'Principal Consultant - Decarbonization Pathways',
                'industry' => 'Classification Society & Advisory',
                'pass_tier' => 'VIP Executive Pass',
                'message' => 'Attending as advisory contributor and participating in Green Shipping session.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subDays(3),
            ],
            [
                'type' => 'awards',
                'full_name' => 'Sunil Prabhakar',
                'email' => 'prabhakar@knkship.com',
                'phone' => '+91 97690 12987',
                'organization' => 'KNK Ship Management',
                'designation' => 'Director - Technical & Crewing',
                'industry' => 'Ship Management',
                'pass_tier' => 'VIP Executive Pass',
                'message' => 'Nominated for Ship Management Company of the Year award.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subDays(4),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Marcus Vance',
                'email' => 'mvance@spamtest.invalid',
                'phone' => '+1 555 019 2831',
                'organization' => 'Unverified Marketing Ltd',
                'designation' => 'Sales Representative',
                'industry' => 'Telemarketing',
                'pass_tier' => 'Standard Delegate Pass',
                'message' => 'Automated solicitation submission.',
                'status' => 'rejected',
                'created_at' => Carbon::now()->subDays(5),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Ananya Roy',
                'email' => 'ananya.roy@grse.co.in',
                'phone' => '+91 98300 45612',
                'organization' => 'Garden Reach Shipbuilders & Engineers Ltd',
                'designation' => 'Deputy General Manager - Corporate Planning',
                'industry' => 'Defense Shipbuilding',
                'pass_tier' => 'VIP Executive Pass',
                'message' => 'Attending with leadership delegation led by Cmde PR Hari.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subDays(6),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Tariq Mansoor',
                'email' => 'tariq.m@nirmonmarine.com',
                'phone' => '+91 98921 78432',
                'organization' => 'Nirmon Marine & Offshore Design Pvt Ltd',
                'designation' => 'Lead Naval Architect',
                'industry' => 'Naval Architecture & Marine Design',
                'pass_tier' => 'Standard Delegate Pass',
                'message' => 'Table top booth representative and technical session participant.',
                'status' => 'pending',
                'created_at' => Carbon::now()->subDays(7),
            ],
            [
                'type' => 'delegate',
                'full_name' => 'Spam Bot Entry',
                'email' => 'test-spam-443@temp-mail.org',
                'phone' => '+00 000 0000',
                'organization' => 'Crypto Trading Bot',
                'designation' => 'Tester',
                'industry' => 'Other',
                'pass_tier' => 'Standard Delegate Pass',
                'message' => 'Promotional link spam.',
                'status' => 'rejected',
                'created_at' => Carbon::now()->subDays(8),
            ],
            [
                'type' => 'speaker',
                'full_name' => 'Punit Oza FICS',
                'email' => 'punit@maritimenxt.com',
                'phone' => '+65 9123 4567',
                'organization' => 'Maritime NXT Singapore',
                'designation' => 'Founder & Director',
                'industry' => 'Maritime Digitalization',
                'pass_tier' => 'Speaker Pass',
                'message' => 'Panelist confirmation for Maritime Outlook 2030 session.',
                'status' => 'approved',
                'created_at' => Carbon::now()->subDays(9),
            ],
        ];

        foreach ($samples as $item) {
            Registration::updateOrCreate(
                ['email' => $item['email']],
                $item
            );
        }
    }
}
